#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\DemoController::demonicAction

demoRoute:
  path: /demo
  controller: App\Controller\DemoController::demonicAction

heroList:
  path: /hero/list
  controller: App\Controller\HeroController::list

heroCreate:
  path: /hero/create
  controller: App\Controller\HeroController::create

heroGet:
  path: /hero/get/{id}
  controller: App\Controller\HeroController::get

heroUpdate:
  path: /hero/update/{id}
  controller: App\Controller\HeroController::update

heroDelete:
  path: /hero/delete/{id}
  controller: App\Controller\HeroController::delete

decrease:
  path: /hero/decrease
  controller: App\Controller\HeroController::decrease
  # methods: GET|PATCH|POST|HEAD
  schemes: [http]

categoryCreate:
  path: /category/create
  controller: App\Controller\CategoryController::create

categoryGet:
  path: /category/get/{id}
  controller: App\Controller\CategoryController::get

categoryUpdate:
  path: /category/update/{id}
  controller: App\Controller\CategoryController::update

categoryListByType:
  path: /category/list/{target}
  controller: App\Controller\CategoryController::listByTarget
  # methods: GET|PATCH|POST|HEAD
  schemes: [http]

categoryList:
  path: /category/list
  controller: App\Controller\CategoryController::list
  # methods: GET|PATCH|POST|HEAD
  schemes: [http]

categoryDelete:
  path: /category/delete
  controller: App\Controller\CategoryController::delete

placeList:
  path: /place/list
  controller: App\Controller\PlaceController::list

placeCreate:
  path: /place/create
  controller: App\Controller\PlaceController::create

placeGet:
  path: /place/get/{id}
  controller: App\Controller\PlaceController::get

placeUpdate:
  path: /place/update/{id}
  controller: App\Controller\PlaceController::update

placeDelete:
  path: /place/delete/{id}
  controller: App\Controller\PlaceController::delete

routeCreate:
  path: /route/create
  controller: App\Controller\RouteController::create

routeList:
  path: /route/list
  controller: App\Controller\RouteController::list

routeGet:
  path: /route/get/{id}
  controller: App\Controller\RouteController::get

routeUpdate:
  path: /route/update/{id}
  controller: App\Controller\RouteController::update

routeDelete:
  path: /route/delete/{id}
  controller: App\Controller\RouteController::delete

routeToPlaceExists:
  path: /route/exists/{place}/{direction}
  controller: App\Controller\RouteController::routeToPlaceExists

routePlace:
  path: /route/place/{place}
  controller: App\Controller\RouteController::place

routeDirections:
  path: /route/directions
  controller: App\Controller\RouteController::getDirections

